# Generated by Django 2.2.12 on 2020-05-12 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200510_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version_of',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='project.Project', verbose_name='version of'),
        ),
    ]
