# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-03 04:21
from __future__ import unicode_literals
import logging

from django.db import migrations
from audio.models import audio_processing

def regenerate_audio_waveforms(apps, schema_editor):
    Audio = apps.get_model("audio", "Audio")
    for audio in Audio.objects.all():
        try:
            audio_processing(audio)
        except IOError:
            logging.warning('IOError with audio %r', audio.name)


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(regenerate_audio_waveforms),
    ]
