# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:41
from __future__ import unicode_literals

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20161203_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(max_length=250, upload_to=audio.models.audio_file_upload_to, verbose_name='audio'),
        ),
    ]
