# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 14:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20180316_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.CharField(choices=[('pop', 'pop'), ('rock', 'rock'), ('jazz', 'jazz'), ('blues', 'blues'), ('folklore', 'folklore'), ('electronic', 'electronic'), ('other', 'other')], max_length=30, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='instrument',
            field=models.CharField(choices=[('voice', 'voice'), ('guitar', 'guitar'), ('electric guitar', 'electric guitar'), ('bass', 'bass'), ('drums', 'drums'), ('saxophone', 'saxophone'), ('piano', 'piano'), ('sinthesizer', 'sinthesizer'), ('electronic', 'electronic'), ('strings', 'other strings'), ('woodwind', 'woodwind'), ('brass', 'brass'), ('multiple', 'multiple'), ('other', 'other')], max_length=30, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='license',
            field=models.CharField(choices=[('CC-BY-SA-4.0', 'Creative Commons Attribution-ShareAlike 4.0 International')], default='CC-BY-SA-4.0', max_length=30, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='use_type',
            field=models.CharField(choices=[('track', 'track'), ('loop', 'loop'), ('song', 'song'), ('sample', 'sample'), ('other', 'other')], max_length=30, verbose_name='type'),
        ),
    ]
