# Generated by Django 2.2.13 on 2020-06-16 20:45
from django.db import migrations, models
from audio.models import calculate_hashsum

def set_default_hash(apps, schema_editor):
    Audio = apps.get_model('audio', 'Audio')
    for audio in Audio.objects.all():
        print("Prossesing audio: %s ..." % audio.slug)
        try:
            audio.hashsum = calculate_hashsum(audio.audio.path)
            audio.save()
        except FileNotFoundError:
            print("Audio '%s' file not found: '%s'" % (audio.slug, audio.audio.path))


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20200521_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='hashsum',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RunPython(set_default_hash)
    ]
