# Generated by Django 2.2.12 on 2020-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_audio_hashsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='hashsum',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
