# Generated by Django 4.1.13 on 2025-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_auto_20200619_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='instrument',
            field=models.CharField(choices=[('voice', 'voice'), ('guitar', 'guitar'), ('electric guitar', 'electric guitar'), ('bass', 'bass'), ('drums', 'drums'), ('saxophone', 'saxophone'), ('piano', 'piano'), ('sinthesizer', 'sinthesizer'), ('electronic', 'electronic'), ('strings', 'other strings'), ('woodwind', 'woodwind'), ('brass', 'brass'), ('violin', 'violin'), ('multiple', 'multiple'), ('other', 'other')], max_length=30, verbose_name='instrument'),
        ),
    ]
