# Generated by Django 5.2.12 on 2026-03-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_alter_audio_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='source_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to='audio.audio', verbose_name='source audio'),
        ),
    ]
